#!/usr/bin/env bash

# check if the argunment is not provided
if [ -z "$1" ]; then
    echo "Argument not provided."
else
    export VPC_ID="$1"
fi

# delete our vpc

aws ec2 delete-vpc --vpc-id $VPC_ID
